/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'mercury-blue': '#af50ff',
        'ghost-blue': '#e1bdff',
        'deep-space': '#090909',
        'midnight-slate': '#0c0c10',
        graphite: '#454545',
        lead: '#6b6b6b',
        starlight: '#f7f9fa',
        silver: '#828384',
        plum: '#7f56d9',
        ash: '#f0f0f0',
        iron: '#333333',
        cinder: '#423738',
        'storm-gray': '#475467',
        aubergine: '#271635',
      },
      fontFamily: {
        display: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        body: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'serif-accent': ['"Playfair Display"', 'serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        caption: ['12px', { lineHeight: '1.5', letterSpacing: '0.24px' }],
        'body-sm': ['14px', { lineHeight: '1.5', letterSpacing: '0.28px' }],
        body: ['16px', { lineHeight: '1.5', letterSpacing: '0.16px' }],
        subheading: ['18px', { lineHeight: '1.4' }],
        'heading-sm': ['21px', { lineHeight: '1.35' }],
        heading: ['32px', { lineHeight: '1.2' }],
        'heading-lg': ['49px', { lineHeight: '1.15' }],
        display: ['65px', { lineHeight: '1.1', letterSpacing: '0.65px' }],
      },
      fontWeight: {
        w360: '360',
        w420: '420',
        w480: '480',
        w530: '530',
      },
      spacing: {
        4: '4px',
        8: '8px',
        12: '12px',
        16: '16px',
        20: '20px',
        24: '24px',
        32: '32px',
        40: '40px',
        56: '56px',
        72: '72px',
        80: '80px',
        112: '112px',
        128: '128px',
      },
      borderRadius: {
        card: '0px',
        input: '8px',
        btn: '9999px',
        'btn-lg': '9999px',
        container: '19.2px',
      },
      maxWidth: {
        page: '1200px',
      },
    },
  },
  plugins: [],
};
