import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const TEMPLATES = [
  {
    title: 'Toscane & Cinque Terre',
    slug: 'toscane-cinque-terre',
    description: 'Rijdend door heuvels vol wijnranken, middeleeuwse steden en de kleurrijke kustdorpjes van Cinque Terre.',
    emoji: '🍷',
    startLocation: 'Florence, Italy',
    destination: 'La Spezia, Italy',
    days: 7,
    budget: 1200,
    travelStyle: 'comfort',
    highlights: 'Florence, Siena, San Gimignano, Pisa, Cinque Terre',
    priceEur: 4.99,
    featured: true,
    totalCost: 1100,
    totalDistance: 320,
    stops: JSON.stringify([
      { name: 'Florence', country: 'Italy', lat: 43.7696, lng: 11.2558 },
      { name: 'Siena', country: 'Italy', lat: 43.3188, lng: 11.3307 },
      { name: 'San Gimignano', country: 'Italy', lat: 43.4676, lng: 11.0432 },
      { name: 'Pisa', country: 'Italy', lat: 43.7228, lng: 10.4017 },
      { name: 'Cinque Terre', country: 'Italy', lat: 44.1461, lng: 9.6439 },
    ]),
    itinerary: JSON.stringify([
      { day: 1, location: 'Florence', activities: ['Uffizi Galerij bezoeken', 'Ponte Vecchio', 'Piazza della Signoria'], accommodation: 'Hotel Davanzati' },
      { day: 2, location: 'Florence', activities: ['Duomo beklimmen', 'Oltrarno wijk verkennen', 'Boboli tuinen'], accommodation: 'Hotel Davanzati' },
      { day: 3, location: 'Siena', activities: ['Piazza del Campo', 'Siena Duomo', 'Wijndegustatie Chianti'], accommodation: 'Agriturismo Siena' },
      { day: 4, location: 'San Gimignano', activities: ['Middeleeuwse torens', 'Vernaccia wijn proeven', 'Dag-trip Volterra'], accommodation: 'Hotel Leon Bianco' },
      { day: 5, location: 'Pisa', activities: ['Scheve Toren', 'Piazza dei Miracoli', 'Lungarno wandeling'], accommodation: 'Hotel Bologna Pisa' },
      { day: 6, location: 'Cinque Terre', activities: ['Riomaggiore verkennen', 'Kustpad wandeling naar Manarola', 'Vernazza haven'], accommodation: 'La Spezia hotel' },
      { day: 7, location: 'Cinque Terre', activities: ['Monterosso strand', 'Bootje huren', 'Lokale pesto proeven'], accommodation: '' },
    ]),
    tips: JSON.stringify([
      'Boek de Uffizi Galerij weken op voorhand online',
      'ZTL-zones in Florentijnse steden — parkeer buiten het centrum',
      'Cinque Terre Card voor de trein tussen de dorpjes',
      'Lunch in eenvoudige trattoria\'s, niet op het plein',
    ]),
  },
  {
    title: 'Portugal Kustroute',
    slug: 'portugal-kustroute',
    description: 'Van Lissabon tot de Algarve langs de mooiste kustlijnen van West-Europa — surfdorpen, seafood en gouden kliffen.',
    emoji: '🌊',
    startLocation: 'Lisbon, Portugal',
    destination: 'Faro, Portugal',
    days: 8,
    budget: 1000,
    travelStyle: 'budget',
    highlights: 'Lissabon, Sintra, Nazaré, Porto, Algarve',
    priceEur: 4.99,
    featured: true,
    totalCost: 850,
    totalDistance: 460,
    stops: JSON.stringify([
      { name: 'Lisbon', country: 'Portugal', lat: 38.7223, lng: -9.1393 },
      { name: 'Sintra', country: 'Portugal', lat: 38.7979, lng: -9.3877 },
      { name: 'Nazaré', country: 'Portugal', lat: 39.6015, lng: -8.9896 },
      { name: 'Lagos', country: 'Portugal', lat: 37.1013, lng: -8.6740 },
      { name: 'Faro', country: 'Portugal', lat: 37.0193, lng: -7.9304 },
    ]),
    itinerary: JSON.stringify([
      { day: 1, location: 'Lisbon', activities: ['Alfama wijk', 'Bica tram', 'Fado show'], accommodation: 'Hostel Lisbon' },
      { day: 2, location: 'Lisbon', activities: ['Belém toren', 'Pasteis de Belém', 'LX Factory'], accommodation: 'Hostel Lisbon' },
      { day: 3, location: 'Sintra', activities: ['Palácio da Pena', 'Quinta da Regaleira', 'Cabo da Roca'], accommodation: 'Sintra guesthouse' },
      { day: 4, location: 'Nazaré', activities: ['Grote golven uitzicht', 'Droogvis markt', 'Praia de Nazaré'], accommodation: 'Nazaré pension' },
      { day: 5, location: 'Lagos', activities: ['Ponta da Piedade rotsen', 'Praia Dona Ana', 'Old town'], accommodation: 'Lagos hostel' },
      { day: 6, location: 'Lagos', activities: ['Kajaktour langs grotten', 'Sagres & Cabo de São Vicente'], accommodation: 'Lagos hostel' },
      { day: 7, location: 'Faro', activities: ['Ria Formosa naturpark', 'Ilha Deserta', 'Oldtown kathedraal'], accommodation: 'Faro hotel' },
      { day: 8, location: 'Faro', activities: ['Barreta eiland', 'Lokale markt', 'Afsluiting diner'], accommodation: '' },
    ]),
    tips: JSON.stringify([
      'Huur een auto in Lissabon — openbaar vervoer langs de kust is traag',
      'Pastel de nata eet je nergens beter dan bij Pasteis de Belém',
      'Nazaré grote golven: beste van november tot maart',
      'Algarve is druk in juli-augustus — boek vroeg',
    ]),
  },
  {
    title: 'Schotse Hooglanden',
    slug: 'schotse-hooglanden',
    description: 'Ruige berglandschappen, spoken kastelen, whisky-distilleerderijen en de Loch Ness legende — Schotland op zijn wildst.',
    emoji: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    startLocation: 'Edinburgh, Scotland',
    destination: 'Inverness, Scotland',
    days: 6,
    budget: 900,
    travelStyle: 'adventure',
    highlights: 'Edinburgh, Glencoe, Loch Lomond, Loch Ness, Inverness',
    priceEur: 4.99,
    featured: true,
    totalCost: 800,
    totalDistance: 400,
    stops: JSON.stringify([
      { name: 'Edinburgh', country: 'Scotland', lat: 55.9533, lng: -3.1883 },
      { name: 'Loch Lomond', country: 'Scotland', lat: 56.1083, lng: -4.6139 },
      { name: 'Glencoe', country: 'Scotland', lat: 56.6811, lng: -5.1019 },
      { name: 'Fort William', country: 'Scotland', lat: 56.8198, lng: -5.1052 },
      { name: 'Inverness', country: 'Scotland', lat: 57.4778, lng: -4.2247 },
    ]),
    itinerary: JSON.stringify([
      { day: 1, location: 'Edinburgh', activities: ['Edinburgh Castle', 'Royal Mile', 'Arthur\'s Seat'], accommodation: 'Edinburgh Old Town hostel' },
      { day: 2, location: 'Loch Lomond', activities: ['Nationale Park wandeling', 'Luss dorp', 'Loch Lomond boot'], accommodation: 'Loch Lomond B&B' },
      { day: 3, location: 'Glencoe', activities: ['Glencoe Valley wandeling', 'Signal Rock', 'Three Sisters bergpanorama'], accommodation: 'Glencoe hostel' },
      { day: 4, location: 'Fort William', activities: ['Ben Nevis (optioneel beklimmen)', 'Jacobite Trein (Harry Potter brug)', 'Neptune\'s Staircase'], accommodation: 'Fort William guesthouse' },
      { day: 5, location: 'Inverness', activities: ['Loch Ness bezoek', 'Urquhart Castle', 'Culloden Battlefield'], accommodation: 'Inverness hostel' },
      { day: 6, location: 'Inverness', activities: ['Clava Cairns', 'Whisky distilleerderij tour', 'Victorian Market'], accommodation: '' },
    ]),
    tips: JSON.stringify([
      'Huur een auto — openbaar vervoer bestaat nauwelijks in de Hooglanden',
      'Midge muggen zijn verschrikkelijk in zomer — breng DEET mee',
      'The Jacobite trein boek je maanden op voorhand',
      'Midges zijn het erg van juni-augustus in de avond',
    ]),
  },
  {
    title: 'Kroatisch Eilandhoppen',
    slug: 'kroatisch-eilandhoppen',
    description: 'Kristalhelder water, middeleeuwse oude steden, verse vis en de beste eilanden van de Adriatische Zee.',
    emoji: '⛵',
    startLocation: 'Split, Croatia',
    destination: 'Dubrovnik, Croatia',
    days: 7,
    budget: 1100,
    travelStyle: 'comfort',
    highlights: 'Split, Hvar, Korčula, Dubrovnik',
    priceEur: 4.99,
    featured: false,
    totalCost: 950,
    totalDistance: 280,
    stops: JSON.stringify([
      { name: 'Split', country: 'Croatia', lat: 43.5081, lng: 16.4402 },
      { name: 'Hvar', country: 'Croatia', lat: 43.1729, lng: 16.4413 },
      { name: 'Korčula', country: 'Croatia', lat: 42.9601, lng: 17.1354 },
      { name: 'Dubrovnik', country: 'Croatia', lat: 42.6507, lng: 18.0944 },
    ]),
    itinerary: JSON.stringify([
      { day: 1, location: 'Split', activities: ['Diocletianus Paleis', 'Stari Grad wandeling', 'Riva promenade'], accommodation: 'Split Old Town hotel' },
      { day: 2, location: 'Split', activities: ['Klis Vesting (Game of Thrones)', 'Marjan Park', 'Diocletianus Mausoleum'], accommodation: 'Split Old Town hotel' },
      { day: 3, location: 'Hvar', activities: ['Veerboot Split→Hvar', 'Stari Grad pleinen', 'Spanjola Fort zonsondergang'], accommodation: 'Hvar Town hotel' },
      { day: 4, location: 'Hvar', activities: ['Lavender velden rondrit', 'Pakleni eilanden snorkelen', 'Hvar nightlife'], accommodation: 'Hvar Town hotel' },
      { day: 5, location: 'Korčula', activities: ['Veerboot naar Korčula', 'Marco Polo geboortestad', 'Moreška zwaarddans'], accommodation: 'Korčula Town guesthouse' },
      { day: 6, location: 'Dubrovnik', activities: ['Veerboot naar Dubrovnik', 'Stadsmuren lopen (2km)', 'Stradun boulevard'], accommodation: 'Dubrovnik hotel' },
      { day: 7, location: 'Dubrovnik', activities: ['Lokrum eiland', 'Game of Thrones tour', 'Banje strand'], accommodation: '' },
    ]),
    tips: JSON.stringify([
      'Boek veerboten op voorhand in zomer — heel druk in juli/augustus',
      'Dubrovnik is duur — eet verder van de muren',
      'Jadrolinija is de betrouwbaarste veerbootmaatschappij',
      'Parkeren in Split is een nachtmerrie — gebruik park & ride',
    ]),
  },
  {
    title: 'Noorse Fjorden',
    slug: 'noorse-fjorden',
    description: 'De spectaculairste natuur van Europa: diepe fjorden, hoge watervallen, middernachtzon en gezellige houten kustdorpjes.',
    emoji: '🏔️',
    startLocation: 'Bergen, Norway',
    destination: 'Flåm, Norway',
    days: 5,
    budget: 1500,
    travelStyle: 'adventure',
    highlights: 'Bergen, Sognefjord, Flåm, Nærøyfjord, Gudvangen',
    priceEur: 4.99,
    featured: true,
    totalCost: 1400,
    totalDistance: 350,
    stops: JSON.stringify([
      { name: 'Bergen', country: 'Norway', lat: 60.3913, lng: 5.3221 },
      { name: 'Voss', country: 'Norway', lat: 60.6291, lng: 6.4160 },
      { name: 'Flåm', country: 'Norway', lat: 60.8634, lng: 7.1184 },
      { name: 'Gudvangen', country: 'Norway', lat: 60.8743, lng: 6.8332 },
    ]),
    itinerary: JSON.stringify([
      { day: 1, location: 'Bergen', activities: ['Bryggen houten huizen UNESCO', 'Fløyen bergbaan', 'Vismarkt'], accommodation: 'Bergen Sentrum hotel' },
      { day: 2, location: 'Voss', activities: ['Voss Gondol naar top', 'Tvinde waterval', 'Paddlesurfen op het meer'], accommodation: 'Voss hotel' },
      { day: 3, location: 'Flåm', activities: ['Flåmsbana trein (UNESCO)', 'Nærøyfjord cruise', 'Ægir Brygghus bierbrouwerij'], accommodation: 'Flåm Camping' },
      { day: 4, location: 'Gudvangen', activities: ['Nærøyfjord kayaken', 'Vikinglandsby bezoek', 'Stegastein uitkijkpunt'], accommodation: 'Gudvangen fjordtell' },
      { day: 5, location: 'Bergen', activities: ['Terugreis via Voss', 'Souvenirshoppen Bryggen', 'Afscheid diner'], accommodation: '' },
    ]),
    tips: JSON.stringify([
      'Noorwegen is duur — kook zelf in camping/Airbnb waar mogelijk',
      'Flåmsbana trein: boek weken vooruit in zomer',
      'Middernachtzon: juli is de beste maand',
      'Fjordenpas: combinatieticket voor boot + trein + bus',
    ]),
  },
  {
    title: 'Andalusië Rondreis',
    slug: 'andalusie-rondreis',
    description: 'Flamenco, Moorse paleizen, witte bergdorpjes en de warmste zon van Spanje — het Zuiden in zijn volle glorie.',
    emoji: '💃',
    startLocation: 'Seville, Spain',
    destination: 'Granada, Spain',
    days: 7,
    budget: 900,
    travelStyle: 'cultural',
    highlights: 'Sevilla, Córdoba, Ronda, Málaga, Granada',
    priceEur: 4.99,
    featured: false,
    totalCost: 780,
    totalDistance: 380,
    stops: JSON.stringify([
      { name: 'Seville', country: 'Spain', lat: 37.3891, lng: -5.9845 },
      { name: 'Córdoba', country: 'Spain', lat: 37.8882, lng: -4.7794 },
      { name: 'Ronda', country: 'Spain', lat: 36.7461, lng: -5.1614 },
      { name: 'Málaga', country: 'Spain', lat: 36.7213, lng: -4.4213 },
      { name: 'Granada', country: 'Spain', lat: 37.1773, lng: -3.5986 },
    ]),
    itinerary: JSON.stringify([
      { day: 1, location: 'Seville', activities: ['Alcázar paleis', 'Sevilla Kathedraal', 'Barrio Santa Cruz'], accommodation: 'Seville Centro hotel' },
      { day: 2, location: 'Seville', activities: ['Flamenco show Tablao', 'Triana wijk markt', 'Torre del Oro'], accommodation: 'Seville Centro hotel' },
      { day: 3, location: 'Córdoba', activities: ['Mezquita-Catedral', 'Judería wijk', 'Alcázar de los Reyes'], accommodation: 'Córdoba Old Town hotel' },
      { day: 4, location: 'Ronda', activities: ['Puente Nuevo brug', 'Taurodroom (oudste arena Spanje)', 'El Tajo kloof wandeling'], accommodation: 'Ronda parador' },
      { day: 5, location: 'Málaga', activities: ['Picasso Museum', 'Alcazaba vesting', 'Pedregalejo strand'], accommodation: 'Málaga hotel' },
      { day: 6, location: 'Granada', activities: ['Alhambra paleis (verplicht voorboeken)', 'Generalife tuinen', 'Albaicín avond'], accommodation: 'Granada hotel' },
      { day: 7, location: 'Granada', activities: ['Sacromonte grotten flamenco', 'Tapas ronde (gratis tapas bij bier)', 'Mirador San Nicolás'], accommodation: '' },
    ]),
    tips: JSON.stringify([
      'Alhambra tickets maanden op voorhand boeken — je komt er anders niet in',
      'Granada geeft gratis tapas bij elk drankje — eet hier zo veel mogelijk',
      'Middag (14u-17u) is dodelijk heet in zomer — rust dan',
      'Rij niet in Sevilla centrum — parkeer bij het station',
    ]),
  },
  {
    title: 'Praag & Wenen Klassieker',
    slug: 'praag-wenen-klassieker',
    description: 'Twee van de mooiste steden van Centraal-Europa in één roadtrip: Barok, bier, Sacher-torte en ongelofelijke architectuur.',
    emoji: '🏰',
    startLocation: 'Prague, Czech Republic',
    destination: 'Vienna, Austria',
    days: 6,
    budget: 800,
    travelStyle: 'cultural',
    highlights: 'Praag, Český Krumlov, Salzburg, Wenen',
    priceEur: 4.99,
    featured: false,
    totalCost: 700,
    totalDistance: 450,
    stops: JSON.stringify([
      { name: 'Prague', country: 'Czech Republic', lat: 50.0755, lng: 14.4378 },
      { name: 'Český Krumlov', country: 'Czech Republic', lat: 48.8128, lng: 14.3175 },
      { name: 'Salzburg', country: 'Austria', lat: 47.8095, lng: 13.0550 },
      { name: 'Vienna', country: 'Austria', lat: 48.2082, lng: 16.3738 },
    ]),
    itinerary: JSON.stringify([
      { day: 1, location: 'Prague', activities: ['Praagse Burcht', 'Karelsbrug', 'Staroměstské náměstí'], accommodation: 'Praag Old Town hotel' },
      { day: 2, location: 'Prague', activities: ['Josefov Joodse wijk', 'Wenceslasplein', 'Lokaal craft bier', 'Beer Geek bar'], accommodation: 'Praag Old Town hotel' },
      { day: 3, location: 'Český Krumlov', activities: ['Middeleeuws UNESCO kasteel', 'Vltava rivier kajakken', 'Barokke tuinen'], accommodation: 'Český Krumlov guesthouse' },
      { day: 4, location: 'Salzburg', activities: ['Mozart Geburtshaus', 'Festung Hohensalzburg', 'Mirabellgarten Sound of Music'], accommodation: 'Salzburg hotel' },
      { day: 5, location: 'Vienna', activities: ['Schönbrunn Paleis', 'Kunsthistorisches Museum', 'Stephansdom'], accommodation: 'Wenen hotel' },
      { day: 6, location: 'Vienna', activities: ['Weense koffiehuizen', 'Naschmarkt', 'Belvedere Klimt schilderijen'], accommodation: '' },
    ]),
    tips: JSON.stringify([
      'Praag is goedkoop — profiteer van de wisselkoers CZK',
      'Weense koffiehuizen zijn gratis om uren in te zitten',
      'Sacher Torte: origineel bij Hotel Sacher, niet in winkelcentrum',
      'Český Krumlov: sla de toeristenwinkels over, ga buiten het kasteel eten',
    ]),
  },
  {
    title: 'Zwitserse Alpen Lus',
    slug: 'zwitserse-alpen-lus',
    description: 'De allermooiste bergpassen van Europa, met panoramatreinen, chocolade fondues en bergmeren zo blauw dat je denkt dat het nep is.',
    emoji: '🍫',
    startLocation: 'Zurich, Switzerland',
    destination: 'Geneva, Switzerland',
    days: 7,
    budget: 2000,
    travelStyle: 'comfort',
    highlights: 'Zurich, Luzern, Interlaken, Zermatt, Genève',
    priceEur: 4.99,
    featured: true,
    totalCost: 1900,
    totalDistance: 420,
    stops: JSON.stringify([
      { name: 'Zurich', country: 'Switzerland', lat: 47.3769, lng: 8.5417 },
      { name: 'Lucerne', country: 'Switzerland', lat: 47.0502, lng: 8.3093 },
      { name: 'Interlaken', country: 'Switzerland', lat: 46.6863, lng: 7.8632 },
      { name: 'Zermatt', country: 'Switzerland', lat: 46.0207, lng: 7.7491 },
      { name: 'Geneva', country: 'Switzerland', lat: 46.2044, lng: 6.1432 },
    ]),
    itinerary: JSON.stringify([
      { day: 1, location: 'Zurich', activities: ['Altstadt rondwandeling', 'Kunsthaus Museum', 'Zürichsee cruise'], accommodation: 'Zurich hotel' },
      { day: 2, location: 'Lucerne', activities: ['Kapellbrücke', 'Löwendenkmal', 'Pilatus bergtop trein'], accommodation: 'Luzern hotel' },
      { day: 3, location: 'Interlaken', activities: ['Jungfraujoch top of Europe', 'Paragliding boven Interlaken', 'Thunersee'], accommodation: 'Interlaken hostel' },
      { day: 4, location: 'Interlaken', activities: ['Grindelwald gletsjer', 'First Cliff Walk', 'Lauterbrunnen waterval vallei'], accommodation: 'Interlaken hostel' },
      { day: 5, location: 'Zermatt', activities: ['Matterhorn uitzicht', 'Gornergrat trein', 'Autovrij dorp slenteren'], accommodation: 'Zermatt hotel' },
      { day: 6, location: 'Geneva', activities: ['Jet d\'Eau fontein', 'CERN bezoek', 'Palais des Nations'], accommodation: 'Genève hotel' },
      { day: 7, location: 'Geneva', activities: ['Vieille Ville', 'Chocolade workshop', 'Lac Léman fietstocht'], accommodation: '' },
    ]),
    tips: JSON.stringify([
      'Swiss Travel Pass bespaart veel op treinen en bergbanen',
      'Jungfraujoch: alleen bij goed weer gaan — controleeer vooraf',
      'Zermatt is autovrij — geen auto nodig, wel duur',
      'Eten in Zwitserland: supermarkt Migros of Coop voor lunch, spaar voor avondeten',
    ]),
  },
  {
    title: 'Dolomiti Bergavontuur',
    slug: 'dolomiti-bergavontuur',
    description: 'De magische roze rotsformaties van Noord-Italië — via ferratas, bergmeren en authentieke Südtirolse keuken.',
    emoji: '🧗',
    startLocation: 'Bolzano, Italy',
    destination: 'Cortina d\'Ampezzo, Italy',
    days: 5,
    budget: 1000,
    travelStyle: 'adventure',
    highlights: 'Bolzano, Alpe di Siusi, Tre Cime di Lavaredo, Cortina',
    priceEur: 4.99,
    featured: false,
    totalCost: 900,
    totalDistance: 220,
    stops: JSON.stringify([
      { name: 'Bolzano', country: 'Italy', lat: 46.4983, lng: 11.3548 },
      { name: 'Alpe di Siusi', country: 'Italy', lat: 46.5436, lng: 11.6362 },
      { name: 'Canazei', country: 'Italy', lat: 46.4774, lng: 11.7735 },
      { name: 'Cortina d\'Ampezzo', country: 'Italy', lat: 46.5404, lng: 12.1357 },
    ]),
    itinerary: JSON.stringify([
      { day: 1, location: 'Bolzano', activities: ['Ötzi ijsman museum', 'Walther Platz', 'Lokale Speck proeven'], accommodation: 'Bolzano hotel' },
      { day: 2, location: 'Alpe di Siusi', activities: ['Grootste hoogvlakte alpenweiden Europa', 'Panoramawandeling', 'Rifugio lunch'], accommodation: 'Alpe di Siusi berghut' },
      { day: 3, location: 'Canazei', activities: ['Passo Pordoi (2239m)', 'Marmolada gletsjer uitzicht', 'Val di Fassa wandeling'], accommodation: 'Canazei hotel' },
      { day: 4, location: 'Cortina', activities: ['Tre Cime di Lavaredo lus (9km)', 'Lago di Misurina', 'Cortina piazza'], accommodation: 'Cortina hotel' },
      { day: 5, location: 'Cortina', activities: ['Cinque Torri via ferrata', 'Lagazuoi kabelbaan', 'Aperitivo afsluiting'], accommodation: '' },
    ]),
    tips: JSON.stringify([
      'Dolomiti Superski pas of Dolomiti wandelkaart kopen bij aankomst',
      'Wegpassen sluiten vroeg in de avond — plan vroeg',
      'Rifugio berghutten hebben geweldig eten voor betaalbare prijs',
      'Tre Cime: vroeg beginnen (7u) om toeristen te ontlopen',
    ]),
  },
  {
    title: 'Griekse Eilanden Klassiek',
    slug: 'griekse-eilanden-klassiek',
    description: 'Santorini zonsondergangen, Mykonos windmolens, historisch Athene en het diepste blauw van de Middellandse Zee.',
    emoji: '🏛️',
    startLocation: 'Athens, Greece',
    destination: 'Santorini, Greece',
    days: 8,
    budget: 1300,
    travelStyle: 'comfort',
    highlights: 'Athene, Mykonos, Naxos, Santorini',
    priceEur: 4.99,
    featured: true,
    totalCost: 1200,
    totalDistance: 500,
    stops: JSON.stringify([
      { name: 'Athens', country: 'Greece', lat: 37.9838, lng: 23.7275 },
      { name: 'Mykonos', country: 'Greece', lat: 37.4467, lng: 25.3289 },
      { name: 'Naxos', country: 'Greece', lat: 37.1035, lng: 25.3765 },
      { name: 'Santorini', country: 'Greece', lat: 36.3932, lng: 25.4615 },
    ]),
    itinerary: JSON.stringify([
      { day: 1, location: 'Athens', activities: ['Akropolis & Parthenon', 'Akropolis Museum', 'Monastiraki markt'], accommodation: 'Athene hotel Plaka' },
      { day: 2, location: 'Athens', activities: ['Nationaal Archeologisch Museum', 'Syntagma wisseling', 'Psyrri avond'], accommodation: 'Athene hotel Plaka' },
      { day: 3, location: 'Mykonos', activities: ['Veerboot Athene-Mykonos', 'Windmolens Kato Mili', 'Little Venice wijkje'], accommodation: 'Mykonos Town hotel' },
      { day: 4, location: 'Mykonos', activities: ['Paradise Beach', 'Delos dagtrip (UNESCO)', 'Mykonos nightlife'], accommodation: 'Mykonos Town hotel' },
      { day: 5, location: 'Naxos', activities: ['Veerboot Mykonos-Naxos', 'Naxos Town kasteel', 'Apollo tempel Portara'], accommodation: 'Naxos hotel' },
      { day: 6, location: 'Naxos', activities: ['Fiets huren door binnenland', 'Plaka strand (8km)', 'Lokale Naxiako kaas proeven'], accommodation: 'Naxos hotel' },
      { day: 7, location: 'Santorini', activities: ['Veerboot Naxos-Santorini', 'Oia zonsondergang (vroeg komen!)', 'Caldera uitzicht'], accommodation: 'Fira hotel' },
      { day: 8, location: 'Santorini', activities: ['Akrotiri opgraving', 'Red Beach', 'Wijnproeving Assyrtiko'], accommodation: '' },
    ]),
    tips: JSON.stringify([
      'Oia zonsondergang: kom 2 uur vroeger — anders sta je 10 rijen diep',
      'Griekse veren: Blue Star Ferries voor eilanden, boek vooraf',
      'Santorini is het duurste eiland — eet op Fira, niet Oia',
      'Athene in augustus: 40 graden, ga vroeg s\'ochtends naar Akropolis',
    ]),
  },
];

async function main() {
  console.log('Seeding trip templates...');

  for (const t of TEMPLATES) {
    await prisma.tripTemplate.upsert({
      where: { slug: t.slug },
      update: t,
      create: { id: `tmpl_${t.slug.replace(/-/g, '_')}`, ...t },
    });
    console.log(`  ✓ ${t.title}`);
  }

  console.log(`Done — ${TEMPLATES.length} templates seeded.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
